### ISSUE TITLE
Bugtesting Kinematics Page

### ISSUE THREAD

**Issue by PhysCal** [PhysCal/PhysCal.github.io#11]
Note: If any problems listed here are simple formatting problems they should be ignored. All listings are also open to discussion at any convenient time.

[x] -When selecting xf as the variable being solved for, xf is listed as one of the values that can be entered. It should be xi instead.

[x]-If possible, the selection boxes for non-split answers should be centered on the screen and not locked to the left.

[x]-Calculate should be capitalized in the calculate buttons (yes I am an anal shitlord)

[x]-I had thought that a drop down menu would be used to switch between a t and d entry box which occupy the same space in the acceleration and time calculations, as opposed to always having separate boxes for each. This would make the page a bit more easy to understand/look at and minimize possible entry issues. 

//Now irrelevant, figured out in Issue #12 
On the same subject of the t and d boxes, the idea you sent me in skype (having the user select either t or d and have the corresponding other variables appear accordingly) seems good at first but I feel it would make things more difficult for the user. Like instead of being able to start filling in variables at whichever point they want they need to decipher whether or not the problem includes a t or a d. Also, unless we add some extra description explaining the absence of the other variables before they appear, it may be confusing to people who aren't yet dialed in to the equations, which is essentially what our audience will be. This is entirely up for discussion and should be brought up in our next talky sesh.

**Comment by StevenPG** [comment]
Yes we'll talk about it some other time.
For some reason, trying to put the variable entires in the middle of the screen is causing everything to not work correctly.
 I'm going to spend some time working on that next.I'll need you to expand on your drop-down menu thing, I don't remember what our original idea was. Just try to expand on it so I can get what your 'vision' is.

**Comment by StevenPG** [comment]
Note: Added it so that when Initial Position begins checked, its respective form also appears on the webpage load. They still dynamically change on selection.
Also, you can click on the ellipses to see what the issue description is that I reference the issue from.
