### ISSUE TITLE
Design Kinematics webpage:

### ISSUE THREAD

**Issue by StevenPG** [PhysCal/PhysCal.github.io#9]
- Title (something more flashy)
- short description via Sam -knwolege
- equation question box (what do you want to calculate)
- procedurally presents relevant variables (inputs)
- submit button appeares
- result box appears with return of submit function
  -optional (dead link) SEE HOUY IZ DUN

**Comment by PhysCal** [comment]
-What do you want to calculate is below the description (separated by a black bar or something for aesthetic purposes)

-Below that will appear the variables in the relevant equation. i.e. for someone calculating xf, from 
xf = xi + vt + at^2, xf is the variable they select to calculate and xi, v, a, and t are all boxes that appear and must have values entered into them.

-Once variables are selected user can hit a submit button to actually calculate their specified answer

-Said answer will appear in an answer box/window below the submit button/boxes with variable values entered into them

-no diks

**Comment by PhysCal** [comment]
-In the highly possible event of the duplication (i.e. user wants to solve for a variable that appears in multiple equations), the page will split in half vertically in the area where variables are being entered.

-On one side of a split will be a possible set of variable entry boxes for one equation, and on the other will be the other possible set. 

-In the event of an acceleration calculation request, one side will hold boxes for t, v, xi, and xf. 
(xf = xi + vt + at^2)

-The other side will hold boxes specifically for vf and vi. There will be a drop down menu for the final box where the user will choose either between the variable d(distance) or the variable t(time). Depending on which of those two the user chooses, the program will either utilize the equation 
vf^2 = vi^2 +2ad (if d is selected), and vf = vi + at (if t is entered).

-In this split case, two submit buttons will appear below the variable entry section; one applying to the left side and one applying to the left (and all equations therein).

-Regardless of the side used the answer should go to a singular answer box placed below the submit and variable entry sections.

**Comment by StevenPG** [comment]
See Kinematics.data for data

**Comment by StevenPG** [comment]
For radio button prettyness, make 3 div sections and left justify? There are 8 variables, maybe 6 divs, 2 above and below each other in the middle left justified, just make it look somewhat less terrible than it currently does

**Comment by StevenPG** [comment]
changes due to server issues with php (see if sam likes changes)
Have all possible options, those not valid when radio button is selected are grayed out

**Comment by PhysCal** [comment]
Kinematics Description: (Certainly up for minor edits later)

Kinematics is the most basic science of motion. Its equations can describe how fast a sprinter runs a race, how high a ball flies in the air, and how fast a rocket must move to reach Mars in a certain time-frame. This section is most useful in solving problems relating to changes in position or velocity over time.
